// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var defaultText = "Click me!";

function prettyPrint(param) {
  return "Im a button of size " + String(200);
}

var Border = /* module */[
  /* widthPx */2,
  /* prettyPrint */prettyPrint
];

var Button = /* module */[
  /* sizePx */200,
  /* defaultText */defaultText,
  /* Border */Border
];

console.log(2);

console.log("Im a button of size " + String(200));

console.log(200);

console.log(2);

var ExitButton = /* module */[
  /* sizePx */200,
  /* defaultText */defaultText,
  /* Border */Border,
  /* exitMessage */"Bye!"
];

console.log(200);

exports.Button = Button;
exports.ExitButton = ExitButton;
/*  Not a pure module */
