// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function familiaToStr(miembroFamiliar) {
  switch (miembroFamiliar.tag | 0) {
    case 0 : 
        return "El padre se llama " + (miembroFamiliar[0] + (" y tiene " + (String(miembroFamiliar[1]) + " años")));
    case 1 : 
        return "La madre se llama " + miembroFamiliar[0];
    case 2 : 
        return "El " + ((
                  miembroFamiliar[2] ? "primer " : ""
                ) + ("hijo se llama " + (miembroFamiliar[0] + (" y tiene " + (String(miembroFamiliar[1]) + " años")))));
    case 3 : 
        return "La " + ((
                  miembroFamiliar[2] ? "primera " : ""
                ) + ("hija se llama " + (miembroFamiliar[0] + (" y tiene " + (String(miembroFamiliar[1]) + " años")))));
    
  }
}

console.log(familiaToStr(/* Padre */Block.__(0, [
            "Juan",
            30
          ])));

console.log(familiaToStr(/* Madre */Block.__(1, ["Andrea"])));

console.log(familiaToStr(/* Hija */Block.__(3, [
            "Clara",
            9,
            true
          ])));

exports.familiaToStr = familiaToStr;
/*  Not a pure module */
