// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function curriedAddFn(a, b) {
  return a + b | 0;
}

function addFive(param) {
  return 5 + param | 0;
}

console.log(addFive(10));

console.log(addFive(20));

exports.curriedAddFn = curriedAddFn;
exports.addFive = addFive;
/*  Not a pure module */
