// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function curriedAddFn(a, $staropt$star, param) {
  var b = $staropt$star !== undefined ? $staropt$star : 0;
  return a + b | 0;
}

var b = 0;

var addFive = 5 + b | 0;

console.log(addFive);

var b$1 = 5;

console.log(5 + b$1 | 0);

exports.curriedAddFn = curriedAddFn;
exports.addFive = addFive;
/*  Not a pure module */
