// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var exampleCoordinate = /* tuple */[
  5,
  10,
  15
];

exports.exampleCoordinate = exampleCoordinate;
/* No side effect */
