// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function dogAge($staropt$star, humanAge, param) {
  var multiplicationFactor = $staropt$star !== undefined ? $staropt$star : 7;
  return Caml_int32.imul(humanAge, multiplicationFactor);
}

console.log(dogAge(undefined, 5, /* () */0));

var humanAge = 5;

exports.dogAge = dogAge;
exports.humanAge = humanAge;
/*  Not a pure module */
