// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function colorToRgb(color) {
  switch (color) {
    case 0 : 
        return "#ffffff";
    case 1 : 
        return "#00ff00";
    case 2 : 
        return "#ff0000";
    case 3 : 
        return "#0000ff";
    case 4 : 
        return "#000000";
    
  }
}

exports.colorToRgb = colorToRgb;
/* No side effect */
