// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var x = 10;

function printOptionalInt(value) {
  if (value !== undefined) {
    return String(value);
  } else {
    return "empty";
  }
}

console.log(printOptionalInt(x));

exports.x = x;
exports.printOptionalInt = printOptionalInt;
/*  Not a pure module */
