// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function printFn(message) {
  console.log(message);
  return /* () */0;
}

exports.printFn = printFn;
/* No side effect */
